### ISSUE TITLE
I can't use it in Angular 13

### ISSUE THREAD

**Issue by tortuc** [BePo65/mat-tristate-checkbox#84]
Uncaught (in promise): Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.
Error: BrowserModule has already been loaded. If you need access to common directives such as NgIf and NgFor from a lazy loaded module, import CommonModule instead.

**Comment by BePo65** [comment]
Ooops, something went wrong, when publishing v13.0.0. Fixed the problem; new version is v13.0.3.
